library(shiny)

# ui.R

shinyUI(fluidPage(
        titlePanel("Body Mass Index Calculator"),
        sidebarLayout(
                sidebarPanel(
                        helpText("Your personal information"),
                        br(),
                        
                        textInput("wt", label = "Your weigth",
                                    value = "75"),
                        
                        radioButtons("wtUnits", label = "Units", 
                                     choices = list("kg", "lb"),
                                     selected = "kg"),
                        
                        textInput("ht", label = "Your height",
                                    value = "175"),
                        
                        radioButtons("htUnits", label = "Units", 
                                     choices = list("cm", "in"),
                                     selected = "cm"),
                        
                        selectInput("nationality", label = "Where are you from?", 
                                    choices = list("Afghanistan", "Aland Islands", 
                                                   "Albania", "Algeria", "American Samoa",
                                                   "Andorra", "Angola", "Anguilla",
                                                   "Antarctica", "Antigua and Barbuda",
                                                   "Argentina", "Armenia", "Aruba",
                                                   "Australia", "Austria", "Azerbaijan",
                                                   "Bahamas", "Bahrain", "Bangladesh",
                                                   "Barbados", "Belarus", "Belgium", 
                                                   "Belize", "Benin", "Bermuda", "Bhutan", 
                                                   "Bolivia", "Bonaire, Sint Eustatius and Saba",
                                                   "Bosnia and Herzegovina", "Botswana",
                                                   "Bouvet Island", "Brazil", 
                                                   "British Indian Ocean Territory", 
                                                   "Brunei Darussalam", "Bulgaria", "Burkina Faso",
                                                   "Burundi", "Cambodia", "Cameroon", "Canada",
                                                   "Cape Verde", "Cayman Islands", 
                                                   "Central African Republic", "Chad", "Chile",
                                                   "China", "Christmas Island", "Cocos (Keeling) Islands",
                                                   "Colombia","Comoros", "Congo", 
                                                   "Congo, the Democratic Republic of the",
                                                   "Cook Islands", "Costa Rica", "Cote d'Ivoire",
                                                   "Croatia", "Cuba", "Curacao", "Cyprus", 
                                                   "Czech Republic", "Denmark", "Djibouti",
                                                   "Dominica", "Dominican Republic", "Ecuador",
                                                   "Egypt", "El Salvador", "Equatorial Guinea", 
                                                   "Eritrea", "Estonia", "Ethiopia",
                                                   "Falkland Island (Malvinas)", "Faroe Islands",
                                                   "Fiji", "Finland", "France", "French Guiana",
                                                   "French Polynesia", "French Southern Territories",
                                                   "Gabon", "Gambia", "Georgia", "Germany",
                                                   "Ghana", "Gibraltar", "Greece", "Greenland",
                                                   "Grenada", "Guadeloupe", "Guam", "Guatemala",
                                                   "Guernsey", "Guinea", "Ginea-Bissau", "Guyana",
                                                   "Haiti", "Heard Island and McDonald Islands",
                                                   "Holy See (Vatican City State)", "Honduras",
                                                   "Hong Kong", "Hungary", "Iceland", "India",
                                                   "Indonesia", "Iran", "Iraq", "Ireland",
                                                   "Isle of Man", "Israel", "Italy", 
                                                   "Jamaica", "Japan", "Jersey", "Jordan",
                                                   "Kazakhstan", "Kenya", "Kiribati",
                                                   "Korea, Democratic People's Republic of",
                                                   "Korea, Republic of", "Kuwait", "Kyrgyzstan",
                                                   "Lao People's Democratic Republic",
                                                   "Latvia", "Lebanon", "Lesotho", "Liberia",
                                                   "Libyan Arab Jamahiriya", "Liechtenstein",
                                                   "Lithuania", "Luxembourg", "Macao",
                                                   "Macedonia", "Madagascar", "Malawi",
                                                   "Malaysia", "Maldives", "Mali", "Malta",
                                                   "Marshall Islands", "Martinique",
                                                   "Mauritania", "Mauritius", "Mayotte",
                                                   "Mexico", "Micronesia, Federated States of",
                                                   "Moldova", "Monaco", "Mongolia", "Montenegro",
                                                   "Montserrat", "Morocco", "Mozambique",
                                                   "Myanmar", "Namibia", "Nauru", "Nepal",
                                                   "Netherlands", "New Caledonia", "New Zealand",
                                                   "Nicaragua", "Niger", "Nigeria", "Niue",
                                                   "Norfolk Island", "Northern Mariana Islands",
                                                   "Norway", "Oman", "Pakistan", "Palau",
                                                   "Palestinian Territory, Occupied", "Panama",
                                                   "Papua New Guinea", "Paraguay", "Peru",
                                                   "Philippines", "Pitcairn", "Poland",
                                                   "Portugal", "Puerto Rico", "Qatar",
                                                   "Reunion", "Romania", "Russian Federation",
                                                   "Rwanda", "Saint Barthelemy", 
                                                   "Saint Helena, Ascension and Tristan da Cunha",
                                                   "Saint Kitts and Nevis", "Saint Lucia",
                                                   "Saint Martin (French part)", 
                                                   "Saint Pierre and Miquelon",
                                                   "Saint Vincent and the Grenadines",
                                                   "Samoa", "San Marino", "Sao Tome and Principe",
                                                   "Saudi Arabia", "Senegal", "Serbia", 
                                                   "Seychelles", "Sierra Leone", "Singapore",
                                                   "Sint Maarten (Dutch part)", "Slovakia",
                                                   "Slovenia", "Solomon Islands", "Somalia",
                                                   "South Africa", "South Georgia and the South Sandwich Islands",
                                                   "South Sudan", "Spain", "Sri Lanka", "Sudan",
                                                   "Suriname", "Svalbard and Jan Mayen",
                                                   "Swaziland", "Sweden", "Switzerland",
                                                   "Syrian Arab Republic", "Taiwan",
                                                   "Tajikistan", "Tanzania, United Republic of",
                                                   "Thailand", "Timor-Leste", "Togo",
                                                   "Tokelau", "Tonga", "Trinidad and Tobago",
                                                   "Tunisia", "Turkey", "Turkmenistan", 
                                                   "Turks and Caicos Islands", "Tuvalu",
                                                   "Uganda", "Ukraine", "United Arab Emirates",
                                                   "United Kingdom", "United States", 
                                                   "United States Minor Outlying Islands",
                                                   "Uruguay", "Uzbekistan", "Vanuatu",
                                                   "Venezuela, Bolivarian Republic of",
                                                   "Viet Nam", "Virgin Islands, British", 
                                                   "Virgin Islands, U.S.", "Wallis and Futuna",
                                                   "Western Sahara", "Yemen", "Zambia",
                                                   "Zimbabwe", selected = "Argentina")),
                        
                        submitButton("Submit")
                ),
                mainPanel(
                        tabsetPanel(
                                tabPanel("Main",
                                        h3("Your personal information"),
                                        textOutput("text1"),
                                        br(),
                                        textOutput("text2"),
                                        br(),
                                        br(),
                                        h3("Your results"),
                                        textOutput("text3"),
                                        plotOutput("plot"),
                                        br(),
                                        br(),
                                        h3("World Health Organization Data"),
                                        p("The information showed here was extracted from the
                                        World Health Organization Global Body Mass Index 
                                        Database. Find more info in this website."),
                                        a(href="here", "http://apps.who.int/bmi/index.jsp"),
                                        p(strong("Disclaimer:"), "The information shared here may
                                        be incomplete or outdated. This was the latest 
                                        available data in the WHO website the 12th October 2015."),
                                        br(),
                                        br(),
                                        h4("Your indicated that:"),
                                        textOutput("text4"),
                                        br(),
                                        p("This is the latest data from your country:"),
                                        tableOutput("table1"),
                                        br(),
                                        br(),
                                        h4("Average values of Calories/day intake in your country
                                        region"),
                                        plotOutput("whoPlot")
                                        ),
                                tabPanel("Documentation",
                                         h3("How does the Body Mass Calculator Works?"),
                                         p("The user inputs his/her weight (kg or lb) and height (cm or in),
                                           and the system calculates the BMI in kg/m2 according to the 
                                           following formula:"),
                                         helpText("BMI = wt / ht^2"),
                                         p("For this purpose, the input data is transformed, if needed, to 
                                           the International System of Units (also known as SI)."),
                                         p("Wanna know more about BMI? Check it ", 
                                           a(href="https://en.wikipedia.org/wiki/Body_mass_index", "here"), "."),
                                         p("The user also inputs his/her nationality and the latest available 
                                           information (up to October 2015) from the Global Mass Index 
                                           Database from the World Health Organization is displayed."),
                                         p("Wanna know more about the Global BMI Database? Check it ", 
                                           a(href="http://apps.who.int/bmi/index.jsp", "here"), ".")
                                         )
                )
        )
        )
))